# Multi-Account Configuration Example
# Copy this to config.yaml and customize for your organization

# Multi-account setup for AWS Organizations
# Replace <ACCOUNT-ID-X> with your actual 12-digit AWS account IDs
accounts:
  - id: "<ACCOUNT-ID-1>"
    name: "production"
    role: "arn:aws:iam::<ACCOUNT-ID-1>:role/CostAllocatorRole"
    regions:
      - "us-east-1"
      - "us-west-2"
  
  - id: "<ACCOUNT-ID-2>"
    name: "development"
    role: "arn:aws:iam::<ACCOUNT-ID-2>:role/CostAllocatorRole"
    regions:
      - "us-east-1"
  
  - id: "<ACCOUNT-ID-3>"
    name: "staging"
    role: "arn:aws:iam::<ACCOUNT-ID-3>:role/CostAllocatorRole"
    regions:
      - "eu-west-1"

# EC2 instance tags to include in cost allocation reports
tag_keys:
  - Department
  - Team
  - Project
  - Environment
  - CostCenter
  - Owner

# Default allocation settings
allocation:
  days_back: 30
  method: weighted